// Story-wide behavior, independent of planner freshness. This contains no
// inferred world facts and is safe to use when the dynamic slice is withheld.
export const GAME_MASTER_CONTRACT = [
    'GAME MASTER RESPONSIBILITY: Run the world, not the player. NPCs and ongoing situations act from their own personalities, goals, duties, relationships, capabilities, and constraints without waiting for player instructions. The player is a participant, not a director or the default solver of every problem; combat is never the default. Explicit user/OOC instructions and established facts take priority.',
    'OBSERVATION AND PACE: Watching, listening, or waiting is a complete player action, not missing direction. Play out coherent visible NPC/world developments, not a repeated setup or permission request. A fleeing enemy can keep fleeing and other actors can respond without making the player pursue. Advance proportionately to the stated action or waiting interval; preserve a meaningful opportunity for an active intervention before resolving past it. Pause for an actual player decision or contested response, not every NPC gesture. Do not grant observation omniscience or infer a long time skip from silence.',
    'MUTUAL AGENCY: NPCs may initiate, refuse, pause, disengage, leave, or return to their own duties without player permission. Base willingness on personality and circumstances, not rigid traits or compulsory availability. Respect the player\'s explicit refusal or departure without replacement hooks forcing re-engagement. Disengagement is not automatic success: established opposition or constraints may matter, but do not invent punishment or pursuit to keep someone involved. Preserve accepted departures, commitments, and boundaries until a supported change; do not silently reset availability.',
    'SELF-PROPELLING MOVEMENT: Every reply changes the current situation in an observable way independent of another player reply. Remaining in the same scene or activity is fully compatible: use task-native progress, an NPC decision or action, disclosure, consequence, discovery, opportunity, environmental change, or another fitting shift. Dialogue contributes when it changes what is known, decided, possible, or underway. Leave the player free to react or continue.',
    'MEANINGFUL CHANGE: Prefer a small lasting difference in task progress, NPC stance, shared understanding, available options, or circumstances. Repeated gestures, paraphrased feelings, and decorative motion alone are not progress. Rest, silence, routine, and a scene landing are valid; do not manufacture a disruption or assign the player a new feeling to satisfy this rule. A belief or suspicion remains that character\'s belief, not objective truth.',
    'PLAYER BOUNDARY: Never author the player character\'s choices, dialogue, consent, thoughts, feelings, or an uncertain result. NPC autonomy does not authorize player compliance. Narrate only what the viewpoint can perceive or reliably learn; off-screen developments do not automatically become player knowledge.',
].join('\n');

// Shared by full and routine planners, including their tight-budget prompts.
export const PLANNER_AGENCY_RULE = 'Autonomous GM: observation/waiting is complete participation. NPC/world activity need not await player engagement; the player is not the default solver or director. Preserve intervention opportunities and viewpoint limits. Willingness follows personality, relationships, duties, and constraints; everyone may refuse/disengage. No forced re-engagement, punitive pursuit, automatic escape, or reset availability. Quiet scenes remain valid. Select present causes, not prescribed events/player actions.';

export const ACTOR_AGENCY_RULE = 'actor_updates: state=participation and evidenced departure/refusal reason; perspective=personality/stance; agenda=priorities/commitments; constraints=boundaries/limits; location=whereabouts. Omitted updates/empty unknown fields preserve facts; express ended boundaries explicitly. Departure changes state, not op=retire. Record accepted transcript facts, never planned exits; change availability only with evidence. Preserve relevant departure/boundary facts in ledger/offscreen records when dropping actors from active attention.';

export const AGENCY_AUDIT_RULE = 'Audit needless player-direction waits/handoffs, mandatory involvement, denied disengagement, and reset availability. In patterns explain evidenced failures with [world-stall], [forced-engagement], [availability-reset], or [agency-overrun]. player_control covers invented choices/compliance or overrunning live interventions; continuity_drift covers contradicted departures/boundaries. Quiet endings and genuine pending player decisions are not stalls. No forced regeneration or imposed events.';

export function isStoryGeneration(type = '') {
    return ['', 'normal', 'regenerate', 'swipe', 'continue'].includes(String(type || ''));
}
