import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const source = await readFile(new URL('../extension/index.js', import.meta.url), 'utf8');
const stateSource = await readFile(new URL('../extension/state.js', import.meta.url), 'utf8');
const template = await readFile(new URL('../extension/settings.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../extension/style.css', import.meta.url), 'utf8');
const manifest = JSON.parse(await readFile(new URL('../manifest.json', import.meta.url), 'utf8'));

test('injected guidance is authoritative context without forcing plot outcomes', () => {
    assert.match(stateSource, /authoritative context guidance for the next roleplay reply/);
    assert.match(stateSource, /not as a command to force a plot event/);
    assert.match(stateSource, /Do not omit a supported influence merely because its outcome is uncertain/);
    assert.match(stateSource, /without declaring an unestablished result/);
    assert.match(stateSource, /do not freeze NPCs or the wider world until the user explicitly requests movement/);
    assert.match(stateSource, /current focus or silence is not a veto on supported external developments/);
});

test('extension UI and interceptor use SillyTavern third-party-compatible registration', () => {
    assert.equal(manifest.loading_order, 65);
    assert.match(source, /new URL\('\.\/settings\.html', import\.meta\.url\)/);
    assert.match(source, /#extensions_settings2[\s\S]*#extensions_settings/);
    assert.match(source, /globalThis\.livingWorldGuideGenerateInterceptor\s*=\s*livingWorldGuideGenerateInterceptor/);
    assert.match(source, /new MutationObserver\(attemptMount\)/);
    assert.match(source, /UI_MOUNT_TIMEOUT_MS\s*=\s*30000/);
    assert.match(source, /eventSource\.on\(event_types\.EXTENSIONS_FIRST_LOAD, startUIMounting\)/);
    assert.match(source, /getCharacterCardFields, saveSettingsDebounced } from '\/script\.js'/);
    assert.match(source, /import \{ extension_settings \} from '\/scripts\/extensions\.js'/);
    assert.match(source, /if \(!Object\.hasOwn\(settings, key\)\) settings\[key\] = value/);
    assert.doesNotMatch(source, /extension_settings\[EXTENSION_ID\] = \{ \.\.\.DEFAULT_SETTINGS/);
    assert.match(template, /class="inline-drawer-toggle inline-drawer-header"/);
    assert.match(template, /class="inline-drawer-icon fa-solid fa-circle-chevron-down down"/);
    assert.match(template, /id="living-world-guide-settings" class="extension_container living-world-guide-panel"/);
    assert.match(template, /class="text_pole" data-setting="connection"/);
    assert.match(template, /value="__direct_custom__"/);
    assert.match(template, /value="__direct_openrouter__"/);
    assert.doesNotMatch(template, /data-setting="source"|data-setting="profile"|data-setting="provider"/);
    assert.match(source, /function applyAnalysisConnectionChoice/);
    assert.match(source, /function rememberDirectSettings/);
    assert.match(source, /function restoreDirectSettings/);
    assert.match(source, /function refreshConnectionProfiles/);
    assert.match(source, /async function collectHostContext/);
    assert.match(source, /getWorldInfoPrompt\(chatForWorldInfo/);
    assert.doesNotMatch(source, /Object\.entries\(context\.extensionPrompts/);
    assert.match(source, /\['description', 'personality', 'scenario', 'persona'\]/);
    assert.match(source, /result\.cardSystemReference = String\(fields\.system\)/);
    assert.match(source, /function parseAnalysisResponse/);
    assert.match(source, /active model structured request failed; retrying with a JSON-only prompt/);
    assert.match(source, /direct model structured request failed; retrying with a JSON-only prompt/);
    assert.match(source, /JSON\.stringify\(ANALYSIS_SCHEMA\.value\)/);
    assert.match(source, /text: submittedNote\.text/);
    assert.match(source, /Instruction saved/);
    assert.match(source, /function stopAnalysis\(\)/);
    assert.match(source, /analysisAbortController\.abort/);
    assert.match(source, /waitForAbortable\(generateRaw/);
    assert.match(source, /PLANNER_RESPONSE_TOKENS = 3000/);
    assert.match(source, /activeSource === 'openrouter'/);
    assert.match(source, /model\.provider === 'openrouter'\) return await send\(false\)/);
    assert.match(source, /isGuidanceUsable\(state, messages/);
    assert.match(source, /buildPromptPayload\(state/);
    assert.match(source, /function renderBoard/);
    assert.match(source, /globalThis\.continuityMemoryBridge/);
    assert.match(source, /snapshot\?\.status === 'current'/);
    assert.match(source, /scratchpad-possibilities/);
    assert.match(source, /scratchpad-continuity/);
    assert.match(source, /scratchpad-ledger/);
    assert.match(source, /configurePromptManagerInjection\(promptManager, s, payload\)/);
    assert.match(source, /injectionPosition: 'at-depth', injectionDepth: 2, injectionRole: 'user'/);
    assert.match(source, /context\.chat\?\.length \? context\.chat : chat/);
    assert.match(source, /Planning is performed between turns, after assistant replies/);
    assert.doesNotMatch(source, /livingWorldGuideGenerateInterceptor[\s\S]{0,900}analyzeNow/);
    assert.doesNotMatch(source, /Guidance unavailable; retrying in/);
    assert.doesNotMatch(source, /abort\(true\)/);
    assert.match(source, /function randomPlannerSeed/);
    assert.match(source, /function isolatePlannerGenerationData/);
    assert.match(source, /generateData\.seed = variationSeed/);
    assert.match(source, /generateData\.sampler_seed = variationSeed/);
    assert.match(source, /generateData\.custom_prompt_post_processing = ''/);
    assert.match(source, /'stop', 'stopping_strings', 'logit_bias', 'tools', 'tool_choice'/);
    assert.match(source, /generateRaw\(\{[\s\S]{0,320}instructOverride: true/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,500}void analyzeNow/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,180}generationRevision\+\+/);
    assert.match(source, /function waitForBackgroundPlanner/);
    assert.match(source, /await waitForBackgroundPlanner\(\)/);
    assert.match(source, /allowNextUserMessage: true/);
    assert.match(source, /const matchesPlannedTurn = guard\.allowNextUserMessage/);
    assert.match(source, /MESSAGE_RECEIVED[\s\S]{0,500}scheduleBackgroundAnalysis\(250\)/);
    assert.doesNotMatch(source, /guidanceGateStopSequence|guidanceGateActive/);
    assert.match(source, /CHAT_COMPLETION_PROMPT_READY, ensureChatCompletionRequestGuidance/);
    assert.match(source, /CHAT_COMPLETION_SETTINGS_READY, ensureProviderChatRequestGuidance/);
    assert.match(source, /GENERATE_AFTER_COMBINE_PROMPTS, ensureTextCompletionRequestGuidance/);
    assert.match(source, /Guidance inserted into request/);
    assert.match(source, /Guidance verified in provider request/);
    assert.match(source, /Guidance confirmed in returned reply/);
    assert.match(source, /CONFIRMED — the provider returned an assistant reply from a request containing this exact guide/);
    assert.doesNotMatch(template, /data-setting="wait-first"/);
    assert.doesNotMatch(source, /firstAnalysisWaitMs|waitForFirstAnalysis/);
    assert.match(source, /analyzeNow\(\{ force: true, rebuild: existing\.scene\.status !== 'uninitialized' \}\)/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,250}scheduleBackgroundAnalysis/);
    assert.match(template, /data-action="stop"[^>]*disabled/);
    assert.match(template, /data-action="reset-settings"/);
    assert.match(source, /function resetSettingsToDefaults/);
    assert.match(source, /Object\.assign\(s, \{ \.\.\.DEFAULT_SETTINGS \}\)/);
    assert.match(source, /Settings reset to defaults/);
    assert.match(template, /data-role="analysis-status"/);
    assert.match(template, /data-setting="injection-position"/);
    assert.match(template, /data-setting="injection-depth"[^>]*value="2"/);
    assert.match(template, /data-setting="injection-role"/);
    assert.match(template, /Planner Scratchpad/);
    assert.match(template, /Use Continuity context when available/);
    assert.match(template, /data-role="scratchpad-continuity"/);
    assert.match(template, /data-role="scratchpad-scene"/);
    assert.match(template, /data-role="scratchpad-guidance"/);
    assert.match(template, /data-role="scratchpad-request-verification"/);
    assert.match(template, /data-role="scratchpad-objectives"/);
    assert.match(template, /data-role="scratchpad-possibilities"/);
    assert.match(template, /data-role="scratchpad-ledger"/);
    assert.match(template, /AI-assisted instruction/);
    assert.match(template, /Tale Fairy will understand whether this is a suggestion, correction, canon detail, or hard exclusion/);
    assert.doesNotMatch(template, /data-setting="note-kind"/);
    assert.match(source, /AI-ASSISTED USER NOTE - classify and apply appropriately/);
    assert.match(source, /result\?\.note_resolution/);
    assert.match(source, /Note not applied · try again/);
    assert.match(source, /Tale Fairy is unsure how to apply this instruction/);
    assert.match(source, /persistClarifiedNote\(text, kind\)/);
    assert.doesNotMatch(source, /analyzeNow\(\{ note: `\[\$\{kind\}\]/);
    assert.doesNotMatch(template, /data-action="recalculate"/);
    assert.doesNotMatch(source, /data-action="recalculate"/);
    assert.match(styles, /\.living-world-guide-card/);
    assert.match(styles, /\.living-world-guide-panel \.text_pole/);
    assert.match(styles, /\.living-world-guide-board section/);
});
