import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const source = await readFile(new URL('../extension/index.js', import.meta.url), 'utf8');
const continuitySource = await readFile(new URL('../extension/continuity.js', import.meta.url), 'utf8');
const stateSource = await readFile(new URL('../extension/state.js', import.meta.url), 'utf8');
const template = await readFile(new URL('../extension/settings.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../extension/style.css', import.meta.url), 'utf8');
const manifest = JSON.parse(await readFile(new URL('../manifest.json', import.meta.url), 'utf8'));

test('manifest identifies the adaptive planning release', () => {
    assert.equal(manifest.version, '0.11.34');
    assert.equal(manifest.js, 'extension/index.js?v=0.11.34');
    assert.equal(manifest.css, 'extension/style.css?v=0.11.34');
});

test('injection sends layered authorial control while concrete realization and future setup stay private', () => {
    assert.match(stateSource, /Conditional authorial direction/);
    assert.match(stateSource, /AUTHORIAL INTENT/);
    assert.match(stateSource, /APPLY WHEN:/);
    assert.match(stateSource, /DO NOT APPLY WHEN:/);
    assert.match(stateSource, /STORY FUNCTION:/);
    assert.match(stateSource, /IMPACT ENVELOPE:/);
    assert.match(stateSource, /binding at the level of narrative purpose/);
    assert.match(stateSource, /Tale Fairy controls narrative function, pressure, and scale/);
    assert.match(stateSource, /realize exact events, NPC actions, dialogue, outcomes, and prose/);
    assert.match(stateSource, /IMMEDIATE ACTION:/);
    assert.match(stateSource, /AUTHORIZED SCOPE:/);
    assert.doesNotMatch(stateSource, /DYNAMIC SCORE:|DRAMATIC SCORE:|SURPRISE LATITUDE:/);
    assert.match(stateSource, /HOLD may complete the activity naturally/);
    assert.match(stateSource, /PACING:/);
    assert.match(stateSource, /Do not reuse the discarded reply/);
    assert.doesNotMatch(stateSource, /within two sentences|Answer once|recap|repeated dialogue|show only that outcome/);
    assert.match(stateSource, /<tale-fairy-context>/);
    assert.doesNotMatch(stateSource, /SUGGESTED ROUTE|ROUTE OUTCOME|SELECTED IMMEDIATE ROUTE|ALTERNATIVE ROUTE/);
    assert.doesNotMatch(stateSource, /GROUNDING:|EXECUTION:/);
    assert.match(stateSource, /planHorizons\.items/);
    assert.doesNotMatch(stateSource, /TIME HORIZONS/);
    assert.match(stateSource, /guideCandidates = null, guideIndex = 0, regeneration = false/);
});

test('extension UI and interceptor use SillyTavern third-party-compatible registration', () => {
    assert.equal(manifest.loading_order, 65);
    assert.match(source, /new URL\('\.\/settings\.html', import\.meta\.url\)/);
    assert.match(source, /globalThis\.taleFairyRuntime = Object\.freeze/);
    assert.match(source, /Tale Fairy runtime \$\{RUNTIME_VERSION\} loaded/);
    assert.doesNotMatch(source, / · seed \$\{state\.plannerSeed\}/);
    assert.match(source, /#extensions_settings2[\s\S]*#extensions_settings/);
    assert.match(source, /globalThis\.livingWorldGuideGenerateInterceptor\s*=\s*livingWorldGuideGenerateInterceptor/);
    assert.match(source, /new MutationObserver\(attemptMount\)/);
    assert.match(source, /UI_MOUNT_TIMEOUT_MS\s*=\s*30000/);
    assert.match(source, /eventSource\.on\(event_types\.EXTENSIONS_FIRST_LOAD, startUIMounting\)/);
    assert.match(source, /getCharacterCardFields, saveSettingsDebounced } from '\/script\.js'/);
    assert.match(source, /import \{ extension_settings \} from '\/scripts\/extensions\.js'/);
    assert.match(source, /if \(!Object\.hasOwn\(settings, key\)\) settings\[key\] = value/);
    assert.doesNotMatch(source, /extension_settings\[EXTENSION_ID\] = \{ \.\.\.DEFAULT_SETTINGS/);
    assert.match(template, /class="inline-drawer-toggle inline-drawer-header"/);
    assert.match(template, /class="inline-drawer-icon fa-solid fa-circle-chevron-down down"/);
    assert.match(template, /id="living-world-guide-settings" class="extension_container living-world-guide-panel"/);
    assert.match(template, /class="text_pole" data-setting="connection"/);
    assert.match(template, /value="__direct_custom__"/);
    assert.match(template, /value="__direct_openrouter__"/);
    assert.match(template, /data-action="fetch-models"/);
    assert.match(template, /data-setting="model-list"/);
    assert.match(template, /Model ID \(manual or selected\)/);
    assert.match(template, /data-setting="reasoning"/);
    assert.match(template, /Auto inherits the selected Connection Manager profile or its preset/);
    assert.doesNotMatch(template, /data-setting="source"|data-setting="profile"|data-setting="provider"/);
    assert.match(source, /function applyAnalysisConnectionChoice/);
    assert.match(source, /function rememberDirectSettings/);
    assert.match(source, /function restoreDirectSettings/);
    assert.match(source, /function refreshConnectionProfiles/);
    assert.match(source, /buildPromptPayload\(state, \{ enabled: getSettings\(\)\.enabled, \.\.\.guideSelectionOptions\(state, context\) \}\)/);
    assert.match(source, /async function fetchDirectModels/);
    assert.match(source, /chat_completion_source: openRouter \? 'openrouter' : 'custom'/);
    assert.match(source, /secret_id: s.analysisSecretId/);
    assert.match(source, /\/api\/backends\/chat-completions\/status/);
    assert.match(source, /async function collectHostContext/);
    assert.match(source, /getWorldInfoPrompt\(chatForWorldInfo/);
    assert.doesNotMatch(source, /Object\.entries\(context\.extensionPrompts/);
    assert.match(source, /\['description', 'personality', 'scenario', 'persona'\]/);
    assert.match(source, /result\.cardSystemReference = String\(fields\.system\)/);
    assert.match(source, /function parseAnalysisResponse/);
    assert.match(source, /function analysisErrorMessage/);
    assert.match(source, /messages\.join\('\s*→\s*'\)/);
    assert.match(source, /active model structured request failed; retrying with a JSON-only prompt/);
    assert.match(source, /direct model structured request failed; retrying with a JSON-only prompt/);
    assert.match(source, /planner JSON was incomplete after deterministic recovery; retrying once with explicit correction/);
    assert.match(source, /async function requestAnalysisOnce/);
    assert.match(source, /async function requestAnalysis\(/);
    assert.match(source, /JSON\.stringify\(ANALYSIS_SCHEMA\.value\)/);
    assert.match(source, /text: submittedNote\.text/);
    assert.match(source, /Instruction saved/);
    assert.match(source, /function stopAnalysis\(\)/);
    assert.match(source, /Run the actual Delete guide state operation first/);
    assert.match(source, /async function rebuildGuideState\(\) \{[\s\S]*?await resetState\(\{ rebuilding: true \}\)[\s\S]*?\n\}/);
    assert.match(source, /updateChatMetadata\(clearState\(context\.chatMetadata\), true\)/);
    assert.match(source, /analysisAbortController\.abort/);
    assert.match(source, /waitForAbortable\(generateRaw/);
    assert.doesNotMatch(source, /ANALYSIS_TIMEOUT_MS|analysis timed out/);
    assert.match(source, /PLANNER_RESPONSE_TOKENS = 32768/);
    assert.match(source, /suppressErrorToasts: true/);
    assert.match(source, /activeSource === 'openrouter'/);
    assert.match(source, /const structured = model\.provider !== 'openrouter'/);
    assert.match(source, /analysisReasoningMode: 'auto'/);
    assert.match(source, /function plannerReasoningMode/);
    assert.match(source, /openai_setting_names,[\s\S]*openai_settings,[\s\S]*oai_settings\?\.reasoning_effort/);
    assert.match(source, /\.\.\.reasoningPayload/);
    assert.match(source, /isolatePlannerGenerationData\(generateData, activeReasoningMode, temperature, requestSamplingEnabled\)/);
    assert.match(source, /isGuidanceUsable\(state, messages/);
    assert.match(source, /buildPromptPayload\(state/);
    assert.match(source, /function renderBoard/);
    assert.match(source, /function prepareGenerationGuide/);
    assert.match(source, /replacementGeneration: generationGuideSelection\?\.replacement === true/);
    assert.match(source, /returnedReplyMatchesVerification\(pending, messages, chatId\)/);
    assert.match(source, /function guideTurnKey/);
    assert.match(source, /swipeGuideCursors\.get\(turnKey\)/);
    assert.match(source, /swipeGuideCursors\.set\(turnKey, index\)/);
    assert.match(source, /MESSAGE_SWIPED[\s\S]{0,900}existingSwipeSelected[\s\S]{0,500}void analyzeNow\(\{ messages, allowOneUserAppend: true \}\)/);
    assert.match(source, /Number\(selected\.swipe_id\) < selected\.swipes\.length/);
    assert.match(source, /type === 'swipe' \|\| type === 'regenerate'/);
    assert.match(source, /\(previousIndex \+ 1\) % candidates\.length/);
    assert.match(source, /state\.lastRequestVerification\?\.guideCandidates/);
    assert.match(source, /state\.lastRequestVerification\?\.canonConstraints/);
    assert.match(source, /canonConstraints: loadState\(context\.chatMetadata\)\.canonConstraints/);
    assert.match(source, /generationGuideSelection\.usable \? generationGuideSelection\.candidates : \[\]/);
    assert.match(source, /regeneration: generationGuideSelection\.regeneration/);
    assert.match(source, /variationCue: generationGuideSelection\.variationCue/);
    assert.match(source, /variationCue: swipe \? randomVariationNonce\(\) : 0/);
    assert.match(source, /const retrySource = generationRetrySource\(messages, swipe\)/);
    assert.match(source, /guidesForDiscardedAssistant\(state, retrySource, chatId\)/);
    assert.match(source, /const alignedUsable = !swipe && isGuidanceUsable/);
    assert.match(source, /\(alignedUsable \? state\.nextGuides : retryCandidates\)/);
    assert.match(source, /regeneration: swipe \|\| retryUsable/);
    assert.match(source, /replacement: swipe/);
    assert.match(source, /could not place current guidance in the provider request/);
    assert.match(source, /containsPlannerMarker\(eventData\?\.chat\)/);
    assert.match(source, /containsPlannerMarker\(generateData\)/);
    assert.match(source, /MESSAGE_SENT[\s\S]{0,300}analyzeNow allows exactly one appended user turn/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,180}(?:generationRevision\+\+|cancelRunningAnalysis)/);
    assert.doesNotMatch(source, /internalAnalysisRequests/);
    assert.match(source, /globalThis\.continuityMemoryBridge/);
    assert.match(source, /readContinuityBridge\(context, bridge, \{ allowStale \}\)/);
    assert.match(source, /allowStaleContinuity: true/);
    assert.match(continuitySource, /snapshot\?\.status === 'current'/);
    assert.match(continuitySource, /snapshot\?\.status === 'stale'/);
    assert.match(continuitySource, /continuity context compacted/);
    assert.match(continuitySource, /export async function waitForContinuityBridge/);
    assert.match(source, /optionalContinuityContextWhenReady/);
    assert.match(source, /scratchpad-possibilities/);
    assert.match(source, /scratchpad-continuity/);
    assert.match(source, /scratchpad-ledger/);
    assert.match(source, /function readableScratchpadGuidance/);
    assert.match(source, /Recovery: the planner omitted ranked guides/);
    assert.match(source, /configurePromptManagerInjection\(promptManager, s, payload\)/);
    assert.match(source, /injectionPosition: 'at-depth', injectionDepth: 1, injectionRole: 'user'/);
    assert.match(source, /previousContextVersion > 0 && previousContextVersion < 4/);
    assert.match(source, /previousContextVersion > 0 && previousContextVersion < 5/);
    assert.match(source, /previousContextVersion > 0 && previousContextVersion < 6/);
    assert.match(source, /settings\.contextSettingsVersion = DEFAULT_SETTINGS\.contextSettingsVersion/);
    assert.match(source, /inlineLatestUser: s\.injectionPosition === 'at-depth'/);
    assert.match(template, /<option value="user">User \(default\)<\/option>/);
    assert.match(source, /export async function livingWorldGuideGenerateInterceptor/);
    assert.doesNotMatch(source, /livingWorldGuideGenerateInterceptor[\s\S]{0,1200}await analyzeNow/);
    assert.match(source, /Planning never blocks generation/);
    assert.doesNotMatch(source, /Planner retrying in|guidanceGateActive|guidanceGateStopSequence|abort\(true\)/);
    assert.match(source, /function randomVariationNonce/);
    assert.match(source, /function isolatePlannerGenerationData/);
    assert.match(template, /data-setting="temperature-slider"[^>]*min="0"[^>]*max="2"[^>]*step="0\.05"/);
    assert.match(template, /data-setting="temperature"[^>]*min="0"[^>]*max="2"[^>]*step="0\.05"/);
    assert.match(source, /analysisTemperature: 1/);
    assert.match(source, /function isUnsupportedTemperatureError/);
    assert.match(source, /function retryWithoutUnsupportedTemperature/);
    assert.match(source, /function plannerModelRejectsTemperature/);
    assert.match(source, /gpt-5/);
    assert.match(source, /plannerTemperaturePayload\(temperature, samplingEnabled\)/);
    assert.match(source, /\['temperature', 'top_p', 'frequency_penalty', 'presence_penalty', 'repetition_penalty'\]/);
    assert.match(source, /isolatePlannerGenerationData\(generateData, activeReasoningMode, temperature, requestSamplingEnabled\)/);
    assert.doesNotMatch(source, /generateData\.seed\s*=|generateData\.sampler_seed\s*=|seed:\s*variation/);
    assert.match(source, /generateData\.custom_prompt_post_processing = ''/);
    assert.match(source, /generateData\[key\] = PLANNER_RESPONSE_TOKENS/);
    assert.match(source, /'stop', 'stopping_strings', 'logit_bias', 'tools', 'tool_choice'/);
    assert.match(source, /generateRaw\(\{[\s\S]{0,320}instructOverride: true/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,500}void analyzeNow/);
    assert.match(source, /MESSAGE_RECEIVED[\s\S]{0,900}void analyzeNow\(\{ messages, allowOneUserAppend: true \}\)/);
    assert.match(source, /isAnalysisSourceCurrent\(guard\.fingerprint, guard\.messageCount, chat/);
    assert.doesNotMatch(source, /waitForBackgroundPlanner/);
    assert.doesNotMatch(source, /function backgroundRetryDelay/);
    assert.doesNotMatch(source, /scheduleBackgroundAnalysis/);
    assert.doesNotMatch(source, /roleplayGenerationActive|backgroundTimer|backgroundDelay|allowNextUserMessage/);
    assert.doesNotMatch(source, /MESSAGE_RECEIVED[\s\S]{0,500}scheduleBackgroundAnalysis/);
    assert.match(source, /async function upgradeLegacyPlanIfNeeded/);
    assert.match(source, /async function refreshCurrentPlanIfNeeded/);
    assert.match(source, /refreshCurrentPlanIfNeeded[\s\S]{0,900}isGuidanceUsable\(state, messages, chatId\)/);
    assert.match(source, /refreshCurrentPlanIfNeeded[\s\S]{0,1400}analyzeNow\(\{ messages, allowOneUserAppend: true, waitForContinuity: true \}\)/);
    assert.match(source, /rawVersion < STATE_VERSION/);
    assert.match(source, /LEGACY_UPGRADE_MAX_ATTEMPTS = 1/);
    assert.match(source, /persistedVersion >= STATE_VERSION/);
    assert.match(source, /if \(!completed\) legacyUpgradeAttempts\.delete\(attemptKey\)/);
    assert.match(source, /analyzeNow\(\{ messages, force: true, rebuild: true \}\)/);
    assert.match(source, /void upgradeLegacyPlanIfNeeded\(\)/);
    assert.match(source, /rawState\?\.canonBootstrapPending === true/);
    assert.match(source, /Refresh pending · showing retained plan/);
    assert.match(source, /!upgradePending/);
    assert.match(source, /CHAT_CHANGED[\s\S]{0,900}void refreshCurrentPlanIfNeeded\(\)/);
    assert.match(source, /startUIMounting\(\);\s*\/\/ CHAT_CHANGED[\s\S]{0,500}setTimeout\(\(\) => void refreshCurrentPlanIfNeeded\(\), 0\)/);
    assert.doesNotMatch(source, /setTimeout\(\(\) => \{ renderBoard\(\); scheduleBackgroundAnalysis\(300\); \}, 0\)/);
    assert.match(source, /CHAT_COMPLETION_PROMPT_READY, ensureChatCompletionRequestGuidance/);
    assert.match(source, /CHAT_COMPLETION_SETTINGS_READY, ensureProviderChatRequestGuidance/);
    assert.match(source, /GENERATE_AFTER_COMBINE_PROMPTS, ensureTextCompletionRequestGuidance/);
    assert.match(source, /Guidance inserted into request/);
    assert.match(source, /Guidance verified in provider request/);
    assert.match(source, /Guidance confirmed in returned reply/);
    assert.match(source, /CONFIRMED — the provider returned an assistant reply from a request containing this exact Tale Fairy block/);
    assert.doesNotMatch(template, /data-setting="wait-first"/);
    assert.doesNotMatch(source, /firstAnalysisWaitMs|waitForFirstAnalysis/);
    assert.match(source, /function rebuildState\(\) \{\s*return defaultState\(\);\s*\}/);
    assert.doesNotMatch(source, /rebuilt\.userNotes = previous\.userNotes|rebuilt\.lastRequestVerification = previous\.lastRequestVerification/);
    assert.match(source, /async function rebuildGuideState\(\)[\s\S]{0,500}await resetState\(\{ rebuilding: true \}\)[\s\S]{0,500}analyzeNow\(\{ force: true, rebuild: true, waitForContinuity: true \}\)/);
    assert.match(source, /async function resetState\(\{ rebuilding = false \} = \{\}\)[\s\S]{0,500}pendingRequestVerification = null[\s\S]{0,700}renderBoard\(defaultState\(\)\)/);
    assert.match(source, /Old guide cleared · saving…/);
    assert.match(source, /Old guide cleared · starting planner…/);
    assert.match(template, /data-action="guide"[\s\S]{0,180}data-role="guide-label"/);
    assert.match(template, /data-action="rebuild"/);
    assert.match(source, /async function reevaluateGuideState\(\) \{\s*return analyzeNow\(\{ force: true \}\);\s*\}/);
    assert.match(source, /\[data-action="guide"\][\s\S]{0,180}reevaluateGuideState\(\)/);
    assert.match(source, /\[data-action="rebuild"\][\s\S]{0,180}rebuildGuideState\(\)/);
    assert.match(source, /guideLabel\.textContent = analyzed \? 'Re-evaluate' : 'Guide now'/);
    assert.doesNotMatch(source, /MESSAGE_SENT[\s\S]{0,250}scheduleBackgroundAnalysis/);
    assert.match(template, /data-action="stop"[^>]*disabled/);
    assert.match(template, /data-action="reset-settings"/);
    assert.match(source, /function resetSettingsToDefaults/);
    assert.match(source, /Object\.assign\(s, \{ \.\.\.DEFAULT_SETTINGS \}\)/);
    assert.match(source, /Settings reset to defaults/);
    assert.match(template, /data-role="analysis-status"/);
    assert.doesNotMatch(template, /runtime-version|runtime pending/);
    assert.doesNotMatch(template, /You control pacing in every mode|Tale Fairy keeps six to ten planning horizons/);
    assert.match(template, /data-setting="injection-position"/);
    assert.match(template, /data-setting="injection-depth"[^>]*value="1"/);
    assert.match(template, /data-setting="injection-role"/);
    assert.match(template, /Planner Scratchpad/);
    assert.match(template, /Use Continuity context when available/);
    assert.match(template, /data-role="scratchpad-continuity"/);
    assert.match(template, /data-role="scratchpad-scene"/);
    assert.match(template, /data-role="scratchpad-next-guides"/);
    assert.match(template, /data-role="scratchpad-pathways"/);
    assert.match(template, /data-role="scratchpad-horizons"/);
    assert.match(template, /data-role="scratchpad-guidance"/);
    assert.match(template, /data-role="scratchpad-request-verification"/);
    assert.match(template, /data-role="scratchpad-objectives"/);
    assert.match(template, /data-role="scratchpad-possibilities"/);
    assert.match(template, /data-role="scratchpad-ledger"/);
    assert.match(template, /No generated scene state yet\./);
    assert.match(template, /No generated story frame yet\./);
    assert.match(template, /No generated next guides yet\./);
    assert.match(template, /No generated pathways yet\./);
    assert.match(template, /No generated planning horizons yet\./);
    assert.match(source, /const generatedValue = value => analyzed \? value : ''/);
    assert.match(source, /No generated narrative events yet\./);
    assert.match(template, /AI-assisted instruction/);
    assert.match(template, /Tale Fairy will understand whether this is a suggestion, correction, canon detail, or hard exclusion/);
    assert.doesNotMatch(template, /data-setting="note-kind"/);
    assert.match(source, /AI-ASSISTED USER NOTE - classify and apply appropriately/);
    assert.match(source, /result\?\.note_resolution/);
    assert.match(source, /Note not applied · try again/);
    assert.match(source, /Tale Fairy is unsure how to apply this instruction/);
    assert.match(source, /persistClarifiedNote\(text, kind\)/);
    assert.doesNotMatch(source, /analyzeNow\(\{ note: `\[\$\{kind\}\]/);
    assert.doesNotMatch(template, /data-action="recalculate"/);
    assert.doesNotMatch(source, /data-action="recalculate"/);
    assert.match(styles, /\.living-world-guide-card/);
    assert.match(styles, /\.living-world-guide-panel \.text_pole/);
    assert.match(styles, /\.living-world-guide-board section/);
});
